### ISSUE TITLE
failed to load plugin

### ISSUE THREAD

**Issue by ccharname** [cumany/obsidian-editing-toolbar#57]
great work 
but i can't start the plugin after installing from the market
the only clue is :failed to load plugin editing-toolbar

obsidian version: v1.1.9

**Comment by cumany** [comment]
The file may not be downloaded completely due to network , so we suggest uninstalling the plugin and getting it installed again.
If it doesn't work, we suggest downloading main.js directly from [github](https://github.com/cumany/obsidian-editing-toolbar/releases) and putting it in the plugin directory `.obsidian\plugins\editing-toolbar\

**Comment by ccharname** [comment]
according to your advice, the problem is sloved.
download main.js for github and put it at plugin dir.
thank u very much.
great job
